# Example config for running batch_synthesize

parent_dir: '.' # Directory containing subdirectories of all trained models

targets: # Each entry contains a target class and the weight epoch to use for the model
    - [2S1,      500]
    - [BMP2,     1000]
    - [BRDM_2    500]
    - [BTR_60,   750]
    - [BTR70,    750]
    - [D7,       1500]
    - [T62,      1000]
    - [T72,      950]
    - [ZIL131,   500]
    - [ZSU_23_4, 1000]

num_synths: 1000

db:
    name: mstar2
    targets: 'targets'
    synthetics: 'synthetics'

setup:
    random_seed: 1234
